language: node_js
node_js:
  - '12'
  - '14'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
cache:
  directory:
    - $HOME/.yarn/bin
install:
  - yarn install
script:
  - yarn lint
  - yarn build
  - yarn test
